/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database;


import cn.hlvan.manager.database.tables.ApplyFinance;
import cn.hlvan.manager.database.tables.LimitTime;
import cn.hlvan.manager.database.tables.Order;
import cn.hlvan.manager.database.tables.OrderEssay;
import cn.hlvan.manager.database.tables.Permission;
import cn.hlvan.manager.database.tables.Picture;
import cn.hlvan.manager.database.tables.Role;
import cn.hlvan.manager.database.tables.RolePermission;
import cn.hlvan.manager.database.tables.TradeRecord;
import cn.hlvan.manager.database.tables.User;
import cn.hlvan.manager.database.tables.UserMoney;
import cn.hlvan.manager.database.tables.UserOrder;
import cn.hlvan.manager.database.tables.UserPermission;
import cn.hlvan.manager.database.tables.UserRole;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>zhulin</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APPLY_FINANCE_PRIMARY = Indexes0.APPLY_FINANCE_PRIMARY;
    public static final Index LIMIT_TIME_PRIMARY = Indexes0.LIMIT_TIME_PRIMARY;
    public static final Index ORDER_PRIMARY = Indexes0.ORDER_PRIMARY;
    public static final Index ORDER_ESSAY_PRIMARY = Indexes0.ORDER_ESSAY_PRIMARY;
    public static final Index PERMISSION_PRIMARY = Indexes0.PERMISSION_PRIMARY;
    public static final Index PERMISSION_UK_CODE_SYSTEM = Indexes0.PERMISSION_UK_CODE_SYSTEM;
    public static final Index PICTURE_PRIMARY = Indexes0.PICTURE_PRIMARY;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index ROLE_PERMISSION_PRIMARY = Indexes0.ROLE_PERMISSION_PRIMARY;
    public static final Index TRADE_RECORD_PRIMARY = Indexes0.TRADE_RECORD_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_UK_ACCOUNT = Indexes0.USER_UK_ACCOUNT;
    public static final Index USER_UK_NUMBER = Indexes0.USER_UK_NUMBER;
    public static final Index USER_MONEY_NEWINDEX1 = Indexes0.USER_MONEY_NEWINDEX1;
    public static final Index USER_MONEY_PRIMARY = Indexes0.USER_MONEY_PRIMARY;
    public static final Index USER_ORDER_IDX_ORDER_CODE = Indexes0.USER_ORDER_IDX_ORDER_CODE;
    public static final Index USER_ORDER_PRIMARY = Indexes0.USER_ORDER_PRIMARY;
    public static final Index USER_PERMISSION_PRIMARY = Indexes0.USER_PERMISSION_PRIMARY;
    public static final Index USER_ROLE_PRIMARY = Indexes0.USER_ROLE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index APPLY_FINANCE_PRIMARY = Internal.createIndex("PRIMARY", ApplyFinance.APPLY_FINANCE, new OrderField[] { ApplyFinance.APPLY_FINANCE.ID }, true);
        public static Index LIMIT_TIME_PRIMARY = Internal.createIndex("PRIMARY", LimitTime.LIMIT_TIME, new OrderField[] { LimitTime.LIMIT_TIME.ID }, true);
        public static Index ORDER_PRIMARY = Internal.createIndex("PRIMARY", Order.ORDER, new OrderField[] { Order.ORDER.ID }, true);
        public static Index ORDER_ESSAY_PRIMARY = Internal.createIndex("PRIMARY", OrderEssay.ORDER_ESSAY, new OrderField[] { OrderEssay.ORDER_ESSAY.ID }, true);
        public static Index PERMISSION_PRIMARY = Internal.createIndex("PRIMARY", Permission.PERMISSION, new OrderField[] { Permission.PERMISSION.ID }, true);
        public static Index PERMISSION_UK_CODE_SYSTEM = Internal.createIndex("uk_code_system", Permission.PERMISSION, new OrderField[] { Permission.PERMISSION.CODE, Permission.PERMISSION.SYSTEM_ID }, true);
        public static Index PICTURE_PRIMARY = Internal.createIndex("PRIMARY", Picture.PICTURE, new OrderField[] { Picture.PICTURE.ID }, true);
        public static Index ROLE_PRIMARY = Internal.createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index ROLE_PERMISSION_PRIMARY = Internal.createIndex("PRIMARY", RolePermission.ROLE_PERMISSION, new OrderField[] { RolePermission.ROLE_PERMISSION.ID }, true);
        public static Index TRADE_RECORD_PRIMARY = Internal.createIndex("PRIMARY", TradeRecord.TRADE_RECORD, new OrderField[] { TradeRecord.TRADE_RECORD.ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_UK_ACCOUNT = Internal.createIndex("uk_account", User.USER, new OrderField[] { User.USER.ACCOUNT }, true);
        public static Index USER_UK_NUMBER = Internal.createIndex("uk_number", User.USER, new OrderField[] { User.USER.NUMBER }, true);
        public static Index USER_MONEY_NEWINDEX1 = Internal.createIndex("NewIndex1", UserMoney.USER_MONEY, new OrderField[] { UserMoney.USER_MONEY.USER_ID }, true);
        public static Index USER_MONEY_PRIMARY = Internal.createIndex("PRIMARY", UserMoney.USER_MONEY, new OrderField[] { UserMoney.USER_MONEY.ID }, true);
        public static Index USER_ORDER_IDX_ORDER_CODE = Internal.createIndex("idx_order_code", UserOrder.USER_ORDER, new OrderField[] { UserOrder.USER_ORDER.ORDER_CODE }, false);
        public static Index USER_ORDER_PRIMARY = Internal.createIndex("PRIMARY", UserOrder.USER_ORDER, new OrderField[] { UserOrder.USER_ORDER.ID }, true);
        public static Index USER_PERMISSION_PRIMARY = Internal.createIndex("PRIMARY", UserPermission.USER_PERMISSION, new OrderField[] { UserPermission.USER_PERMISSION.ID }, true);
        public static Index USER_ROLE_PRIMARY = Internal.createIndex("PRIMARY", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ID }, true);
    }
}
