/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database;


import cn.hlvan.manager.database.tables.Permission;
import cn.hlvan.manager.database.tables.Role;
import cn.hlvan.manager.database.tables.RolePermission;
import cn.hlvan.manager.database.tables.User;
import cn.hlvan.manager.database.tables.UserPermission;
import cn.hlvan.manager.database.tables.UserRole;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in zhulin
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>zhulin.permission</code>.
     */
    public static final Permission PERMISSION = cn.hlvan.manager.database.tables.Permission.PERMISSION;

    /**
     * The table <code>zhulin.role</code>.
     */
    public static final Role ROLE = cn.hlvan.manager.database.tables.Role.ROLE;

    /**
     * The table <code>zhulin.role_permission</code>.
     */
    public static final RolePermission ROLE_PERMISSION = cn.hlvan.manager.database.tables.RolePermission.ROLE_PERMISSION;

    /**
     * The table <code>zhulin.user</code>.
     */
    public static final User USER = cn.hlvan.manager.database.tables.User.USER;

    /**
     * The table <code>zhulin.user_permission</code>.
     */
    public static final UserPermission USER_PERMISSION = cn.hlvan.manager.database.tables.UserPermission.USER_PERMISSION;

    /**
     * The table <code>zhulin.user_role</code>.
     */
    public static final UserRole USER_ROLE = cn.hlvan.manager.database.tables.UserRole.USER_ROLE;
}
