/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database.tables;


import cn.hlvan.manager.database.Indexes;
import cn.hlvan.manager.database.Keys;
import cn.hlvan.manager.database.Zhulin;
import cn.hlvan.manager.database.tables.records.EssayTypeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 文章领域
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EssayType extends TableImpl<EssayTypeRecord> {

    private static final long serialVersionUID = -1538064025;

    /**
     * The reference instance of <code>zhulin.essay_type</code>
     */
    public static final EssayType ESSAY_TYPE = new EssayType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EssayTypeRecord> getRecordType() {
        return EssayTypeRecord.class;
    }

    /**
     * The column <code>zhulin.essay_type.id</code>.
     */
    public final TableField<EssayTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>zhulin.essay_type.name</code>. 领域名称
     */
    public final TableField<EssayTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "领域名称");

    /**
     * The column <code>zhulin.essay_type.created_at</code>.
     */
    public final TableField<EssayTypeRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>zhulin.essay_type.updated_at</code>.
     */
    public final TableField<EssayTypeRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>zhulin.essay_type</code> table reference
     */
    public EssayType() {
        this(DSL.name("essay_type"), null);
    }

    /**
     * Create an aliased <code>zhulin.essay_type</code> table reference
     */
    public EssayType(String alias) {
        this(DSL.name(alias), ESSAY_TYPE);
    }

    /**
     * Create an aliased <code>zhulin.essay_type</code> table reference
     */
    public EssayType(Name alias) {
        this(alias, ESSAY_TYPE);
    }

    private EssayType(Name alias, Table<EssayTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private EssayType(Name alias, Table<EssayTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "文章领域");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Zhulin.ZHULIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ESSAY_TYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EssayTypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ESSAY_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EssayTypeRecord> getPrimaryKey() {
        return Keys.KEY_ESSAY_TYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EssayTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<EssayTypeRecord>>asList(Keys.KEY_ESSAY_TYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EssayType as(String alias) {
        return new EssayType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EssayType as(Name alias) {
        return new EssayType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EssayType rename(String name) {
        return new EssayType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EssayType rename(Name name) {
        return new EssayType(name, null);
    }
}
