/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database.tables.records;


import cn.hlvan.manager.database.tables.ApplyFinance;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplyFinanceRecord extends UpdatableRecordImpl<ApplyFinanceRecord> implements Record6<Integer, BigDecimal, Integer, Timestamp, Timestamp, Byte> {

    private static final long serialVersionUID = 1538325800;

    /**
     * Setter for <code>zhulin.apply_finance.id</code>. 写手申请打款
     */
    public ApplyFinanceRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.apply_finance.id</code>. 写手申请打款
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zhulin.apply_finance.money</code>. 申请金额
     */
    public ApplyFinanceRecord setMoney(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.apply_finance.money</code>. 申请金额
     */
    public BigDecimal getMoney() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>zhulin.apply_finance.user_id</code>. 用户Id
     */
    public ApplyFinanceRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.apply_finance.user_id</code>. 用户Id
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>zhulin.apply_finance.created_at</code>.
     */
    public ApplyFinanceRecord setCreatedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.apply_finance.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>zhulin.apply_finance.updated_at</code>.
     */
    public ApplyFinanceRecord setUpdatedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.apply_finance.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>zhulin.apply_finance.status</code>. 0-待打款，1-已打款
     */
    public ApplyFinanceRecord setStatus(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.apply_finance.status</code>. 0-待打款，1-已打款
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, BigDecimal, Integer, Timestamp, Timestamp, Byte> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, BigDecimal, Integer, Timestamp, Timestamp, Byte> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ApplyFinance.APPLY_FINANCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return ApplyFinance.APPLY_FINANCE.MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ApplyFinance.APPLY_FINANCE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ApplyFinance.APPLY_FINANCE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ApplyFinance.APPLY_FINANCE.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return ApplyFinance.APPLY_FINANCE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyFinanceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyFinanceRecord value2(BigDecimal value) {
        setMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyFinanceRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyFinanceRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyFinanceRecord value5(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyFinanceRecord value6(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyFinanceRecord values(Integer value1, BigDecimal value2, Integer value3, Timestamp value4, Timestamp value5, Byte value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplyFinanceRecord
     */
    public ApplyFinanceRecord() {
        super(ApplyFinance.APPLY_FINANCE);
    }

    /**
     * Create a detached, initialised ApplyFinanceRecord
     */
    public ApplyFinanceRecord(Integer id, BigDecimal money, Integer userId, Timestamp createdAt, Timestamp updatedAt, Byte status) {
        super(ApplyFinance.APPLY_FINANCE);

        set(0, id);
        set(1, money);
        set(2, userId);
        set(3, createdAt);
        set(4, updatedAt);
        set(5, status);
    }
}
