/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database.tables.records;


import cn.hlvan.manager.database.tables.OrderEassy;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderEassyRecord extends UpdatableRecordImpl<OrderEassyRecord> implements Record13<Integer, Integer, String, String, String, Double, Integer, Integer, String, Timestamp, Timestamp, Byte, String> {

    private static final long serialVersionUID = -1258589519;

    /**
     * Setter for <code>zhulin.order_eassy.id</code>.
     */
    public OrderEassyRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zhulin.order_eassy.user_order_id</code>. 用户订单号id
     */
    public OrderEassyRecord setUserOrderId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.user_order_id</code>. 用户订单号id
     */
    public Integer getUserOrderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>zhulin.order_eassy.order_code</code>. 订单号
     */
    public OrderEassyRecord setOrderCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.order_code</code>. 订单号
     */
    public String getOrderCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zhulin.order_eassy.eassy_tital</code>. 文章标题
     */
    public OrderEassyRecord setEassyTital(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.eassy_tital</code>. 文章标题
     */
    public String getEassyTital() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zhulin.order_eassy.eassy_file</code>. 文件路径
     */
    public OrderEassyRecord setEassyFile(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.eassy_file</code>. 文件路径
     */
    public String getEassyFile() {
        return (String) get(4);
    }

    /**
     * Setter for <code>zhulin.order_eassy.original_level</code>. 原创度
     */
    public OrderEassyRecord setOriginalLevel(Double value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.original_level</code>. 原创度
     */
    public Double getOriginalLevel() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>zhulin.order_eassy.picture_total</code>. 图片数量
     */
    public OrderEassyRecord setPictureTotal(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.picture_total</code>. 图片数量
     */
    public Integer getPictureTotal() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>zhulin.order_eassy.picture_id</code>. 图片id
     */
    public OrderEassyRecord setPictureId(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.picture_id</code>. 图片id
     */
    public Integer getPictureId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>zhulin.order_eassy.notes</code>. 备注
     */
    public OrderEassyRecord setNotes(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.notes</code>. 备注
     */
    public String getNotes() {
        return (String) get(8);
    }

    /**
     * Setter for <code>zhulin.order_eassy.created_at</code>.
     */
    public OrderEassyRecord setCreatedAt(Timestamp value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>zhulin.order_eassy.updated_at</code>.
     */
    public OrderEassyRecord setUpdatedAt(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>zhulin.order_eassy.status</code>. 0-待审核，1-
     */
    public OrderEassyRecord setStatus(Byte value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.status</code>. 0-待审核，1-
     */
    public Byte getStatus() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>zhulin.order_eassy.result</code>. 审核结果
     */
    public OrderEassyRecord setResult(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.order_eassy.result</code>. 审核结果
     */
    public String getResult() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, String, String, Double, Integer, Integer, String, Timestamp, Timestamp, Byte, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, String, String, Double, Integer, Integer, String, Timestamp, Timestamp, Byte, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrderEassy.ORDER_EASSY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrderEassy.ORDER_EASSY.USER_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OrderEassy.ORDER_EASSY.ORDER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OrderEassy.ORDER_EASSY.EASSY_TITAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OrderEassy.ORDER_EASSY.EASSY_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return OrderEassy.ORDER_EASSY.ORIGINAL_LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return OrderEassy.ORDER_EASSY.PICTURE_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return OrderEassy.ORDER_EASSY.PICTURE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return OrderEassy.ORDER_EASSY.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return OrderEassy.ORDER_EASSY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return OrderEassy.ORDER_EASSY.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return OrderEassy.ORDER_EASSY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return OrderEassy.ORDER_EASSY.RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrderCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEassyTital();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getEassyFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getOriginalLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getPictureTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getPictureId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component12() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrderCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEassyTital();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEassyFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getOriginalLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPictureTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPictureId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value2(Integer value) {
        setUserOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value3(String value) {
        setOrderCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value4(String value) {
        setEassyTital(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value5(String value) {
        setEassyFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value6(Double value) {
        setOriginalLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value7(Integer value) {
        setPictureTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value8(Integer value) {
        setPictureId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value9(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value10(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value11(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value12(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord value13(String value) {
        setResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderEassyRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Double value6, Integer value7, Integer value8, String value9, Timestamp value10, Timestamp value11, Byte value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderEassyRecord
     */
    public OrderEassyRecord() {
        super(OrderEassy.ORDER_EASSY);
    }

    /**
     * Create a detached, initialised OrderEassyRecord
     */
    public OrderEassyRecord(Integer id, Integer userOrderId, String orderCode, String eassyTital, String eassyFile, Double originalLevel, Integer pictureTotal, Integer pictureId, String notes, Timestamp createdAt, Timestamp updatedAt, Byte status, String result) {
        super(OrderEassy.ORDER_EASSY);

        set(0, id);
        set(1, userOrderId);
        set(2, orderCode);
        set(3, eassyTital);
        set(4, eassyFile);
        set(5, originalLevel);
        set(6, pictureTotal);
        set(7, pictureId);
        set(8, notes);
        set(9, createdAt);
        set(10, updatedAt);
        set(11, status);
        set(12, result);
    }
}
