/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database.tables.records;


import cn.hlvan.manager.database.tables.Permission;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionRecord extends UpdatableRecordImpl<PermissionRecord> implements Record8<Integer, String, String, String, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1656959379;

    /**
     * Setter for <code>zhulin.permission.id</code>. 权限id
     */
    public PermissionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.permission.id</code>. 权限id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zhulin.permission.code</code>. 权限码
     */
    public PermissionRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.permission.code</code>. 权限码
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zhulin.permission.name</code>. 权限名
     */
    public PermissionRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.permission.name</code>. 权限名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zhulin.permission.description</code>. 权限描述
     */
    public PermissionRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.permission.description</code>. 权限描述
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zhulin.permission.system_id</code>. 系统id
     */
    public PermissionRecord setSystemId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.permission.system_id</code>. 系统id
     */
    public Integer getSystemId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>zhulin.permission.pid</code>. 父id
     */
    public PermissionRecord setPid(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.permission.pid</code>. 父id
     */
    public Integer getPid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>zhulin.permission.created_at</code>.
     */
    public PermissionRecord setCreatedAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.permission.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>zhulin.permission.updated_at</code>.
     */
    public PermissionRecord setUpdatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.permission.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Permission.PERMISSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Permission.PERMISSION.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Permission.PERMISSION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Permission.PERMISSION.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Permission.PERMISSION.SYSTEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Permission.PERMISSION.PID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Permission.PERMISSION.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Permission.PERMISSION.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getSystemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSystemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value5(Integer value) {
        setSystemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value6(Integer value) {
        setPid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord value8(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Integer value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermissionRecord
     */
    public PermissionRecord() {
        super(Permission.PERMISSION);
    }

    /**
     * Create a detached, initialised PermissionRecord
     */
    public PermissionRecord(Integer id, String code, String name, String description, Integer systemId, Integer pid, Timestamp createdAt, Timestamp updatedAt) {
        super(Permission.PERMISSION);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, description);
        set(4, systemId);
        set(5, pid);
        set(6, createdAt);
        set(7, updatedAt);
    }
}
