/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database.tables.records;


import cn.hlvan.manager.database.tables.Picture;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PictureRecord extends UpdatableRecordImpl<PictureRecord> implements Record7<Integer, String, String, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -2042634305;

    /**
     * Setter for <code>zhulin.picture.id</code>.
     */
    public PictureRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.picture.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zhulin.picture.picture_pixel</code>. 图片像素
     */
    public PictureRecord setPicturePixel(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.picture.picture_pixel</code>. 图片像素
     */
    public String getPicturePixel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zhulin.picture.picture_name</code>. 图片名称
     */
    public PictureRecord setPictureName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.picture.picture_name</code>. 图片名称
     */
    public String getPictureName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zhulin.picture.order_eassy_id</code>. 文章id
     */
    public PictureRecord setOrderEassyId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.picture.order_eassy_id</code>. 文章id
     */
    public Integer getOrderEassyId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>zhulin.picture.notes</code>. 备注
     */
    public PictureRecord setNotes(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.picture.notes</code>. 备注
     */
    public String getNotes() {
        return (String) get(4);
    }

    /**
     * Setter for <code>zhulin.picture.created_at</code>.
     */
    public PictureRecord setCreatedAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.picture.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>zhulin.picture.updated_at</code>.
     */
    public PictureRecord setUpdatedAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.picture.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Picture.PICTURE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Picture.PICTURE.PICTURE_PIXEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Picture.PICTURE.PICTURE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Picture.PICTURE.ORDER_EASSY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Picture.PICTURE.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Picture.PICTURE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Picture.PICTURE.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPicturePixel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPictureName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getOrderEassyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPicturePixel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPictureName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getOrderEassyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value2(String value) {
        setPicturePixel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value3(String value) {
        setPictureName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value4(Integer value) {
        setOrderEassyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value5(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord value7(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PictureRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PictureRecord
     */
    public PictureRecord() {
        super(Picture.PICTURE);
    }

    /**
     * Create a detached, initialised PictureRecord
     */
    public PictureRecord(Integer id, String picturePixel, String pictureName, Integer orderEassyId, String notes, Timestamp createdAt, Timestamp updatedAt) {
        super(Picture.PICTURE);

        set(0, id);
        set(1, picturePixel);
        set(2, pictureName);
        set(3, orderEassyId);
        set(4, notes);
        set(5, createdAt);
        set(6, updatedAt);
    }
}
