/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database.tables.records;


import cn.hlvan.manager.database.tables.TradeRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TradeRecordRecord extends UpdatableRecordImpl<TradeRecordRecord> implements Record6<Integer, Integer, String, BigDecimal, Timestamp, String> {

    private static final long serialVersionUID = 1628694861;

    /**
     * Setter for <code>zhulin.trade_record.id</code>.
     */
    public TradeRecordRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.trade_record.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zhulin.trade_record.user_id</code>. 用户订单号id
     */
    public TradeRecordRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.trade_record.user_id</code>. 用户订单号id
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>zhulin.trade_record.trade_info</code>. 交易信息
     */
    public TradeRecordRecord setTradeInfo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.trade_record.trade_info</code>. 交易信息
     */
    public String getTradeInfo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zhulin.trade_record.money</code>. 商家价格
     */
    public TradeRecordRecord setMoney(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.trade_record.money</code>. 商家价格
     */
    public BigDecimal getMoney() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>zhulin.trade_record.created_at</code>.
     */
    public TradeRecordRecord setCreatedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.trade_record.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>zhulin.trade_record.trade_code</code>. 交易相关码
     */
    public TradeRecordRecord setTradeCode(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.trade_record.trade_code</code>. 交易相关码
     */
    public String getTradeCode() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, BigDecimal, Timestamp, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, BigDecimal, Timestamp, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TradeRecord.TRADE_RECORD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TradeRecord.TRADE_RECORD.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TradeRecord.TRADE_RECORD.TRADE_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TradeRecord.TRADE_RECORD.MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TradeRecord.TRADE_RECORD.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TradeRecord.TRADE_RECORD.TRADE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTradeInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTradeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTradeInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTradeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TradeRecordRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TradeRecordRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TradeRecordRecord value3(String value) {
        setTradeInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TradeRecordRecord value4(BigDecimal value) {
        setMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TradeRecordRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TradeRecordRecord value6(String value) {
        setTradeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TradeRecordRecord values(Integer value1, Integer value2, String value3, BigDecimal value4, Timestamp value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TradeRecordRecord
     */
    public TradeRecordRecord() {
        super(TradeRecord.TRADE_RECORD);
    }

    /**
     * Create a detached, initialised TradeRecordRecord
     */
    public TradeRecordRecord(Integer id, Integer userId, String tradeInfo, BigDecimal money, Timestamp createdAt, String tradeCode) {
        super(TradeRecord.TRADE_RECORD);

        set(0, id);
        set(1, userId);
        set(2, tradeInfo);
        set(3, money);
        set(4, createdAt);
        set(5, tradeCode);
    }
}
