/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database.tables.records;


import cn.hlvan.manager.database.tables.UserOrder;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserOrderRecord extends UpdatableRecordImpl<UserOrderRecord> implements Record9<Integer, Integer, String, String, Integer, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1411192091;

    /**
     * Setter for <code>zhulin.user_order.id</code>.
     */
    public UserOrderRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zhulin.user_order.order_id</code>. 订单号id
     */
    public UserOrderRecord setOrderId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.order_id</code>. 订单号id
     */
    public Integer getOrderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>zhulin.user_order.order_code</code>. 订单号
     */
    public UserOrderRecord setOrderCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.order_code</code>. 订单号
     */
    public String getOrderCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zhulin.user_order.order_status</code>. 1：待完成 2：已完成
     */
    public UserOrderRecord setOrderStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.order_status</code>. 1：待完成 2：已完成
     */
    public String getOrderStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zhulin.user_order.user_id</code>. 用户id
     */
    public UserOrderRecord setUserId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.user_id</code>. 用户id
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>zhulin.user_order.user_total</code>. 已上传数量
     */
    public UserOrderRecord setUserTotal(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.user_total</code>. 已上传数量
     */
    public Integer getUserTotal() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>zhulin.user_order.notes</code>. 备注
     */
    public UserOrderRecord setNotes(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.notes</code>. 备注
     */
    public String getNotes() {
        return (String) get(6);
    }

    /**
     * Setter for <code>zhulin.user_order.created_at</code>.
     */
    public UserOrderRecord setCreatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>zhulin.user_order.updated_at</code>.
     */
    public UserOrderRecord setUpdatedAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, Integer, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserOrder.USER_ORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserOrder.USER_ORDER.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserOrder.USER_ORDER.ORDER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserOrder.USER_ORDER.ORDER_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return UserOrder.USER_ORDER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return UserOrder.USER_ORDER.USER_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserOrder.USER_ORDER.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return UserOrder.USER_ORDER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return UserOrder.USER_ORDER.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrderCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUserTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrderCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value2(Integer value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value3(String value) {
        setOrderCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value4(String value) {
        setOrderStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value6(Integer value) {
        setUserTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value7(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value9(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserOrderRecord
     */
    public UserOrderRecord() {
        super(UserOrder.USER_ORDER);
    }

    /**
     * Create a detached, initialised UserOrderRecord
     */
    public UserOrderRecord(Integer id, Integer orderId, String orderCode, String orderStatus, Integer userId, Integer userTotal, String notes, Timestamp createdAt, Timestamp updatedAt) {
        super(UserOrder.USER_ORDER);

        set(0, id);
        set(1, orderId);
        set(2, orderCode);
        set(3, orderStatus);
        set(4, userId);
        set(5, userTotal);
        set(6, notes);
        set(7, createdAt);
        set(8, updatedAt);
    }
}
