/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database.tables.records;


import cn.hlvan.manager.database.tables.User;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = -2023484166;

    /**
     * Setter for <code>zhulin.user.id</code>. 用户id
     */
    public UserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.id</code>. 用户id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zhulin.user.account</code>.
     */
    public UserRecord setAccount(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.account</code>.
     */
    public String getAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zhulin.user.name</code>. 用户名称
     */
    public UserRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.name</code>. 用户名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zhulin.user.password</code>. 用户密码
     */
    public UserRecord setPassword(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.password</code>. 用户密码
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zhulin.user.qq</code>. qq号
     */
    public UserRecord setQq(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.qq</code>. qq号
     */
    public String getQq() {
        return (String) get(4);
    }

    /**
     * Setter for <code>zhulin.user.wechat</code>. 微信号
     */
    public UserRecord setWechat(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.wechat</code>. 微信号
     */
    public String getWechat() {
        return (String) get(5);
    }

    /**
     * Setter for <code>zhulin.user.code</code>. 用户编码
     */
    public UserRecord setCode(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.code</code>. 用户编码
     */
    public String getCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>zhulin.user.address</code>. 用户地址
     */
    public UserRecord setAddress(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.address</code>. 用户地址
     */
    public String getAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>zhulin.user.status</code>. 1-待提交信息，2-待审核，3-审核成功，4-审核失败，5-禁用
     */
    public UserRecord setStatus(Byte value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.status</code>. 1-待提交信息，2-待审核，3-审核成功，4-审核失败，5-禁用
     */
    public Byte getStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>zhulin.user.credit_level</code>. 信用等级
     */
    public UserRecord setCreditLevel(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.credit_level</code>. 信用等级
     */
    public Integer getCreditLevel() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>zhulin.user.type</code>. 用户身份(1-超级管理员，2-管理员，3-商家，4-写手)
     */
    public UserRecord setType(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.type</code>. 用户身份(1-超级管理员，2-管理员，3-商家，4-写手)
     */
    public Byte getType() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>zhulin.user.pid</code>. 用户所属id
     */
    public UserRecord setPid(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.pid</code>. 用户所属id
     */
    public Integer getPid() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>zhulin.user.created_at</code>.
     */
    public UserRecord setCreatedAt(Timestamp value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>zhulin.user.updated_at</code>.
     */
    public UserRecord setUpdatedAt(Timestamp value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>zhulin.user.number</code>. 编号
     */
    public UserRecord setNumber(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.number</code>. 编号
     */
    public String getNumber() {
        return (String) get(14);
    }

    /**
     * Setter for <code>zhulin.user.remark</code>. 备注
     */
    public UserRecord setRemark(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(15);
    }

    /**
     * Setter for <code>zhulin.user.sex</code>. 性别：0-男，1-女
     */
    public UserRecord setSex(Integer value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.sex</code>. 性别：0-男，1-女
     */
    public Integer getSex() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>zhulin.user.age</code>. 年龄
     */
    public UserRecord setAge(Integer value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.age</code>. 年龄
     */
    public Integer getAge() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>zhulin.user.profession</code>. 职业
     */
    public UserRecord setProfession(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.profession</code>. 职业
     */
    public String getProfession() {
        return (String) get(18);
    }

    /**
     * Setter for <code>zhulin.user.good</code>. 擅长领域
     */
    public UserRecord setGood(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.good</code>. 擅长领域
     */
    public String getGood() {
        return (String) get(19);
    }

    /**
     * Setter for <code>zhulin.user.full_time</code>. 0-全职，1-兼职
     */
    public UserRecord setFullTime(Integer value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.full_time</code>. 0-全职，1-兼职
     */
    public Integer getFullTime() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>zhulin.user.pay_picture</code>. 支付宝二维码
     */
    public UserRecord setPayPicture(String value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.pay_picture</code>. 支付宝二维码
     */
    public String getPayPicture() {
        return (String) get(21);
    }

    /**
     * Setter for <code>zhulin.user.start_level</code>. 用户星级别
     */
    public UserRecord setStartLevel(Integer value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.start_level</code>. 用户星级别
     */
    public Integer getStartLevel() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>zhulin.user.email</code>. 邮箱
     */
    public UserRecord setEmail(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String account, String name, String password, String qq, String wechat, String code, String address, Byte status, Integer creditLevel, Byte type, Integer pid, Timestamp createdAt, Timestamp updatedAt, String number, String remark, Integer sex, Integer age, String profession, String good, Integer fullTime, String payPicture, Integer startLevel, String email) {
        super(User.USER);

        set(0, id);
        set(1, account);
        set(2, name);
        set(3, password);
        set(4, qq);
        set(5, wechat);
        set(6, code);
        set(7, address);
        set(8, status);
        set(9, creditLevel);
        set(10, type);
        set(11, pid);
        set(12, createdAt);
        set(13, updatedAt);
        set(14, number);
        set(15, remark);
        set(16, sex);
        set(17, age);
        set(18, profession);
        set(19, good);
        set(20, fullTime);
        set(21, payPicture);
        set(22, startLevel);
        set(23, email);
    }
}
