/*
 * This file is generated by jOOQ.
*/
package cn.hlvan.manager.database.tables.records;


import cn.hlvan.manager.database.tables.UserOrder;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserOrderRecord extends UpdatableRecordImpl<UserOrderRecord> implements Record8<Integer, String, Integer, Integer, Timestamp, Timestamp, Integer, Byte> {

    private static final long serialVersionUID = 409475555;

    /**
     * Setter for <code>zhulin.user_order.id</code>.
     */
    public UserOrderRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zhulin.user_order.order_code</code>. 订单号
     */
    public UserOrderRecord setOrderCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.order_code</code>. 订单号
     */
    public String getOrderCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zhulin.user_order.reserve_total</code>. 预定的文章数量
     */
    public UserOrderRecord setReserveTotal(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.reserve_total</code>. 预定的文章数量
     */
    public Integer getReserveTotal() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>zhulin.user_order.complete</code>. 完成文章数量
     */
    public UserOrderRecord setComplete(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.complete</code>. 完成文章数量
     */
    public Integer getComplete() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>zhulin.user_order.created_at</code>.
     */
    public UserOrderRecord setCreatedAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>zhulin.user_order.updated_at</code>.
     */
    public UserOrderRecord setUpdatedAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>zhulin.user_order.user_id</code>. 用户id
     */
    public UserOrderRecord setUserId(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.user_id</code>. 用户id
     */
    public Integer getUserId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>zhulin.user_order.status</code>. 0待预约，1-待完成，2-已完成，3-已截稿,4-已取消
     */
    public UserOrderRecord setStatus(Byte value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>zhulin.user_order.status</code>. 0待预约，1-待完成，2-已完成，3-已截稿,4-已取消
     */
    public Byte getStatus() {
        return (Byte) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Timestamp, Timestamp, Integer, Byte> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Timestamp, Timestamp, Integer, Byte> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserOrder.USER_ORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserOrder.USER_ORDER.ORDER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserOrder.USER_ORDER.RESERVE_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserOrder.USER_ORDER.COMPLETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserOrder.USER_ORDER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return UserOrder.USER_ORDER.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return UserOrder.USER_ORDER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return UserOrder.USER_ORDER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOrderCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getReserveTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getComplete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrderCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getReserveTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getComplete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value2(String value) {
        setOrderCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value3(Integer value) {
        setReserveTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value4(Integer value) {
        setComplete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value6(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value7(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord value8(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrderRecord values(Integer value1, String value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6, Integer value7, Byte value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserOrderRecord
     */
    public UserOrderRecord() {
        super(UserOrder.USER_ORDER);
    }

    /**
     * Create a detached, initialised UserOrderRecord
     */
    public UserOrderRecord(Integer id, String orderCode, Integer reserveTotal, Integer complete, Timestamp createdAt, Timestamp updatedAt, Integer userId, Byte status) {
        super(UserOrder.USER_ORDER);

        set(0, id);
        set(1, orderCode);
        set(2, reserveTotal);
        set(3, complete);
        set(4, createdAt);
        set(5, updatedAt);
        set(6, userId);
        set(7, status);
    }
}
